import React, { useState } from "react";
import axios from "axios";
import { useDispatch, useSelector } from "react-redux";
import { Navigate, useNavigate } from "react-router-dom";
import { Update } from "../actions/auth";
import Error from "./Error";


const OneTimePassword = ()=>{
    const user = useSelector(state=>state.auth)
    const navigate = useNavigate()
    const dispatch = useDispatch()
    const [error, setError] = useState('')

    function handleVerify (e){
        e.preventDefault()
        let otp = ''
        setError('')
        document.querySelectorAll('.otp form input').forEach(input=>{
            otp += input.value
        })
        axios.post(`${process.env.REACT_APP_SERVER_URL}/twofactorauth`,
            {email:user.email, otp})
        .then(res=>{
            localStorage.setItem('token', res.data.data.token)
            dispatch(Update(res.data.data))
            navigate("/")
            document.querySelectorAll('.otp form input').forEach((input)=>{
                input.value = ''
            })
        })
        .catch(e=>{
            document.querySelectorAll('.otp form input').forEach((input)=>{
                input.value = ''
            })
            setError(e.response.data.error)
        })
    }

    function handleReverify(){
        axios.post(`${process.env.REACT_APP_SERVER_URL}/resetqr`, {
            email: user.email
        }).then(()=>{
            dispatch(Update({...user, verified: false}))
            navigate("/scanqr")
        })
    }

    function moveFocus(e){
        if(e.target.value.length > 0 && e.target.nextSibling){
            e.target.nextSibling.focus()
        }
    }

    if(user.id){
        return (<Navigate to="/"/>)
    } else if(!user.email){
        return (<Navigate to="/signin"/>)
    } else{
        return(
            <div className="otp">
                <h4>Please Enter The One Time Password(OTP) Generated By Your Microsoft Authenticator App</h4>
                <form className="otp-form">
                    <div id="password">
                        <input autoFocus onKeyUp={moveFocus} required type="text" id="digit-1" maxLength="1"></input>
                        <input onKeyUp={moveFocus} required type="text" id="digit-2" maxLength="1"></input>
                        <input onKeyUp={moveFocus} required type="text" id="digit-3" maxLength="1"></input>
                        <input onKeyUp={moveFocus} required type="text" id="digit-4" maxLength="1"></input>
                        <input onKeyUp={moveFocus} required type="text" id="digit-5" maxLength="1"></input>
                        <input onKeyUp={moveFocus} required type="text" id="digit-6" maxLength="1"></input>
                    </div>
                    {error && <Error message={error}/>}
                    <button type="submit" onClick={handleVerify}>Verify</button>
                </form>
                <h4 id="reverify" onClick={handleReverify}>Scan QR again?</h4>
            </div>
        )
    }
}

export default OneTimePassword